<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit954dbd881252d9b6d68a9931b3370d2c
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit954dbd881252d9b6d68a9931b3370d2c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit954dbd881252d9b6d68a9931b3370d2c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit954dbd881252d9b6d68a9931b3370d2c::$classMap;

        }, null, ClassLoader::class);
    }
}
